import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css";
import QueryProvider from "@/providers/query-provider";
import ApiProvider from "@/providers/api-provider";
import SplashScreen from "@/components/splash-screen/splash-screen";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ip Address Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <QueryProvider>
          <ApiProvider>
            <SplashScreen>{children}</SplashScreen>
          </ApiProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
